### ISSUE TITLE
Update elvmak to use LAYOUT_planck_1x2uC after upstream fix

### ISSUE THREAD

**Issue by evillemez** [evillemez/qmk_firmware#1]
https://github.com/qmk/qmk_firmware/pull/5519

Currently using `LAYOUT_planck_grid` and doubling the 2U key... it supposedly works fine, but is a hack.  Should be able to properly use `LAYOUT_planck_1x2uC` after the fix.

**Comment by IsaacElenbaas** [comment]
Was not fixed, that was only 2x2u as I didn't realize the others were broken as well. Copied fix for 1x2uR/L, so those should be fine no matter what (they're just half the 2x2u) but 1x2uC needs testing.

**Comment by evillemez** [comment]
@IsaacElenbaas Thanks so much for the comment, and the work.  I finally got a chance to come back to this and give it a try, seems to be working now.

**Comment by IsaacElenbaas** [comment]
Funny, it wasn't even mine that eventually got merged.

**Comment by evillemez** [comment]
OSS is a wild ride... :)
